name: pos
description: Dart Implementation of the ISO-8583 banking protocol for Point of Sale (POS) Devices.
version: 0.3.8
repository: https://github.com/xclud/dart_pos
homepage: https://pwa.ir

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  iso9797: ^0.0.5
  convert: ^3.1.1

dev_dependencies:
  test: ^1.25.6
  lints: ^4.0.0
